// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.bookstore.domain;

import com.springsource.roo.bookstore.domain.Categories;

privileged aspect Categories_Roo_JavaBean {
    
    public String Categories.getName() {
        return this.Name;
    }
    
    public void Categories.setName(String Name) {
        this.Name = Name;
    }
    
}
