// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.bookstore.domain;

import com.springsource.roo.bookstore.domain.Orders;
import com.springsource.roo.bookstore.domain.OrdersDataOnDemand;
import com.springsource.roo.bookstore.domain.ShippingDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect OrdersDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OrdersDataOnDemand: @Component;
    
    private Random OrdersDataOnDemand.rnd = new SecureRandom();
    
    private List<Orders> OrdersDataOnDemand.data;
    
    @Autowired
    ShippingDataOnDemand OrdersDataOnDemand.shippingDataOnDemand;
    
    public Orders OrdersDataOnDemand.getNewTransientOrders(int index) {
        Orders obj = new Orders();
        setAddress(obj, index);
        setName(obj, index);
        setPostalCode(obj, index);
        return obj;
    }
    
    public void OrdersDataOnDemand.setAddress(Orders obj, int index) {
        String Address = "Address_" + index;
        obj.setAddress(Address);
    }
    
    public void OrdersDataOnDemand.setName(Orders obj, int index) {
        String Name = "Name_" + index;
        obj.setName(Name);
    }
    
    public void OrdersDataOnDemand.setPostalCode(Orders obj, int index) {
        Number postalCode = null;
        obj.setPostalCode(postalCode);
    }
    
    public Orders OrdersDataOnDemand.getSpecificOrders(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Orders obj = data.get(index);
        Long id = obj.getId();
        return Orders.findOrders(id);
    }
    
    public Orders OrdersDataOnDemand.getRandomOrders() {
        init();
        Orders obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Orders.findOrders(id);
    }
    
    public boolean OrdersDataOnDemand.modifyOrders(Orders obj) {
        return false;
    }
    
    public void OrdersDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Orders.findOrdersEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Orders' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Orders>();
        for (int i = 0; i < 10; i++) {
            Orders obj = getNewTransientOrders(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
