// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.bookstore.domain;

import com.springsource.roo.bookstore.domain.ShippingDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ShippingDataOnDemand_Roo_Configurable {
    
    declare @type: ShippingDataOnDemand: @Configurable;
    
}
